/* ROCSTAT - help.c */

#include <stdio.h>

static const char* help_string =
"  rocstat - calculate statistics and create slices of pack files\n"
"\n"
"	  Usage: rocstat [options] file.am\n"
"\n"
"	  Options:\n"
"\n"
"		-2	calculate two-point statistics\n"
"\n"
"		-3	calculate three-point statistics\n"
"\n"
"		-h	print help and exit\n"
"\n"
"		-i	print info about input file\n"
"\n"
"		-p	calculate packing fraction\n"
"\n"
"		-s	create a slice file\n"
"\n"
"		-v	view file on the screen\n"
"\n"
"		-H	create n hotspot locations inside particles\n"
"\n"
"		-B	select the number of particle size bins (default = unset)\n"
"\n"
"		-b	select the number of bins for the statistics calculations\n"
"			(default = 100)\n"
"\n"
"		-d	maximum distance in microns for statistics calculations\n"
"		  	(default = 25%% of the average of the pack dimensions)\n"
"\n"
"		-n	number of random points per bin\n"
"			(default = 1000000 for 2-point and 200000 for 3-point statistics).\n"
"\n"
"		-r	set hotspot radius in voxels\n"
"		  	(default = 1, used to avoid hotspots close to a particle boundary)\n"
"\n"
"	  Examples:\n"
"\n"
"	    Second order statistics:\n"
"\n"
"	      $ rocstat -2 -b 50 -d 200 -n 30000 -o DCPD.sij DCPD.am\n"
"\n"
"	    Third order statistics:\n"
"\n"
"	      $ rocstat -3 -b 100 -d 150 -o DCPD.sijk DCPD.am\n"
"\n"
"	    Packing fraction:\n"
"\n"
"	      $ rocstat -p DCPD.am\n"
"\n"
"	    Create hotspots:\n"
"\n"
"	      $ rocstat -H 10 -r 3 DCPD.am\n"
"\n"
"	    Create an xy slice file for z=50\n"
"\n"
"	      $ rocstat -s xy:50 DCPD.am > slice.dat\n"
"\n"
"	    The slice types that the program recognizes are xy, xz and yz,\n"
"	    always followed by a colon and the number of the slice in the\n"
"	    missing variable, e.g., yz:10 for a yz slice and x=10.\n";

void print_help(){
	fprintf(stderr, "%s", help_string);
}
